package views;

import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Giuseppe Barretta
 */

public class TheFrame extends javax.swing.JFrame {

    /**
     * Creates new form TheFrame
     */
    public TheFrame() {
        initComponents();
    }

    public JMenu getFileMenu() {return fileMenu;}
    public JTextArea getContentTextArea() {return content;}
    public JMenuItem getOpenMenuItem() {return open;}
    public JMenuItem getNewMenuItem() {return New;}
    public JMenuItem getSaveMenuItem() {return save;}
    public JMenuItem getSaveAsMenuItem() {return saveAs;}
    public JTextField getFileNameTextField() {return fileNameTextField;}
    public JTextField getModifiedTextField() {return modifiedTextField;}
    public JSplitPane getSplitPane() {return jSplitPane1;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();
        jSplitPane1 = new javax.swing.JSplitPane();
        fileNameTextField = new javax.swing.JTextField();
        modifiedTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        New = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        saveAs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content.setColumns(20);
        content.setRows(5);
        jScrollPane1.setViewportView(content);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setDividerSize(1);

        fileNameTextField.setEditable(false);
        jSplitPane1.setRightComponent(fileNameTextField);

        modifiedTextField.setEditable(false);
        modifiedTextField.setMinimumSize(new java.awt.Dimension(20, 20));
        jSplitPane1.setLeftComponent(modifiedTextField);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.PAGE_START);

        fileMenu.setText("File");

        open.setText("Open");
        fileMenu.add(open);

        New.setText("New");
        fileMenu.add(New);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        fileMenu.add(save);

        saveAs.setText("Save As");
        fileMenu.add(saveAs);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem New;
    private javax.swing.JTextArea content;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField modifiedTextField;
    private javax.swing.JMenuItem open;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem saveAs;
    // End of variables declaration//GEN-END:variables
}
